<a href="https://colab.research.google.com/github/SaiSuvamPatnaik/NLP-in-Pytorch/blob/main/NLP_IN_PYTORCH_LEARNING.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Creating Custom Embedding layer

In [ ]:
import torch
from torch.autograd import Variable
import torch.nn as nn
import torch.nn.functional as F
import pandas as pd

In [ ]:
str1 = "I am Sai Suvam"
idx = {"I":0,"am":1,"Sai":2,"Suvam":3}
words = str1.split()
res = [idx[i] for i in words]
print(res)

[0, 1, 2, 3]


In [ ]:
emb = nn.Embedding(len(res),5)
res1 = torch.tensor(res,dtype=torch.long)
emb(res1)

tensor([[-0.6644, -0.6022, -0.3188,  0.0688,  1.3071],
        [-1.5990, -0.9050, -0.3704, -1.6161,  0.2591],
        [-1.2532, -2.1773, -1.1917,  0.4732, -0.4044],
        [-0.4601,  1.0004,  1.0516,  1.6927, -1.1280]],
       grad_fn=<EmbeddingBackward0>)

In [ ]:
print(sum(emb(res1)))

tensor([-3.9767, -2.6840, -0.8293,  0.6185,  0.0338], grad_fn=<AddBackward0>)


### Using pre trained word2vec from gensim library

In [ ]:
import gensim

In [ ]:
review_text = "Other useful internals in Gensim 4.0+ include model.wv.index_to_key, a plain list of the key (word) in each index position, and model.wv.key_to_index, a plain dict mapping keys (words) to their index positions. In pre-4.0 versions, the vocabulary was in the vocab field of the Word2Vec model's wv property, as a dictionary, with the keys being each token (word). So there it was just the usual Python for getting a dictionary's length:"
prc = gensim.utils.simple_preprocess(review_text)


In [ ]:
model = gensim.models.Word2Vec(
    window=3,
    min_count=2,
    workers=4,
)

In [ ]:
model.build_vocab([prc])

In [ ]:
model.wv.vocab

{'dictionary': <gensim.models.keyedvectors.Vocab at 0x7feb68dab610>,
 'each': <gensim.models.keyedvectors.Vocab at 0x7feb68dab950>,
 'in': <gensim.models.keyedvectors.Vocab at 0x7feb68d4f9d0>,
 'index': <gensim.models.keyedvectors.Vocab at 0x7feb68d4f0d0>,
 'keys': <gensim.models.keyedvectors.Vocab at 0x7feb68dab550>,
 'model': <gensim.models.keyedvectors.Vocab at 0x7feb68d4f7d0>,
 'of': <gensim.models.keyedvectors.Vocab at 0x7feb68d4f490>,
 'plain': <gensim.models.keyedvectors.Vocab at 0x7feb68d4f450>,
 'the': <gensim.models.keyedvectors.Vocab at 0x7feb68dabbd0>,
 'was': <gensim.models.keyedvectors.Vocab at 0x7feb68dab490>,
 'word': <gensim.models.keyedvectors.Vocab at 0x7feb68dabd10>,
 'wv': <gensim.models.keyedvectors.Vocab at 0x7feb68d4f990>}

In [ ]:
model.train([prc], total_examples=model.corpus_count, epochs=model.epochs)

(23, 350)

In [ ]:
# torch.FloatTensor(model.wv.vectors.shape)

In [ ]:
model.save("./trial.model")

In [ ]:
model.wv.similarity(w1="index", w2="word")

-0.08971252

In [ ]:
import gensim.downloader as api
from gensim.model import KeyedVectors


In [ ]:
mod = api.load("glove-wiki-gigaword-100")

[==================================================] 100.0% 128.1/128.1MB downloaded


In [ ]:
mod.most_similar(positive=["king","women"],negative=["men"])

[('queen', 0.74156653881073),
 ('monarch', 0.7021745443344116),
 ('prince', 0.6327081918716431),
 ('kingdom', 0.6294623613357544),
 ('elizabeth', 0.6115030646324158),
 ('throne', 0.6069279909133911),
 ('emperor', 0.5794594287872314),
 ('father', 0.567244291305542),
 ('son', 0.5642266273498535),
 ('margaret', 0.5641614198684692)]

In [ ]:
mod.vectors[0].shape

(100,)

### PreProcessing in NLP

In [ ]:
import tensorflow as tf
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

sentences = ["I want to go out.",
             " I like to play.",
             " No eating - ",
             "No play!",
            ]
tokenizer = Tokenizer(num_words=100, lower= 1, oov_token="<OOV>")

# tokenizer = Tokenizer(num_words=100, lower= 1)

tokenizer.fit_on_texts(sentences)
word_index = tokenizer.word_index
print(word_index)

{'i': 1, 'to': 2, 'play': 3, 'no': 4, 'want': 5, 'go': 6, 'out': 7, 'like': 8, 'eating': 9}


In [ ]:
sequences = tokenizer.texts_to_sequences(sentences)
print(sentences)
print(word_index)
print(sequences)

['I want to go out.', ' I like to play.', ' No eating - ', 'No play!']
{'i': 1, 'to': 2, 'play': 3, 'no': 4, 'want': 5, 'go': 6, 'out': 7, 'like': 8, 'eating': 9}
[[1, 5, 2, 6, 7], [1, 8, 2, 3], [4, 9], [4, 3]]


In [ ]:
pre_pad = pad_sequences(sequences, padding='pre')
print("\nword_index = ", word_index)
print("\nsequences = ", sequences)
print("\npadded_seq = " )
print(pre_pad)


word_index =  {'i': 1, 'to': 2, 'play': 3, 'no': 4, 'want': 5, 'go': 6, 'out': 7, 'like': 8, 'eating': 9}

sequences =  [[1, 5, 2, 6, 7], [1, 8, 2, 3], [4, 9], [4, 3]]

padded_seq = 
[[1 5 2 6 7]
 [1 8 2 3 0]
 [4 9 0 0 0]
 [4 3 0 0 0]]


In [ ]:
prepad_maxlen_pretrunc = pad_sequences(sequences, padding ="pre", maxlen =4, truncating ="pre")
print(prepad_maxlen_pretrunc)

[[5 2 6 7]
 [1 8 2 3]
 [0 0 4 9]
 [0 0 4 3]]


Custom Vocabulary

In [ ]:
class Vocabulary:
    def __init__(self, name):
        self.name = name
        self.PAD_token = 0   # Used for padding short sentences
        self.SOS_token = 1   # Start-of-sentence token
        self.EOS_token = 2   # End-of-sentence token
        self.word2index = {}
        self.word2count = {}
        self.index2word = {self.PAD_token: "PAD", self.SOS_token: "SOS", self.EOS_token: "EOS"}
        self.num_words = 3
        self.num_sentences = 0
        self.longest_sentence = 0

    def add_word(self, word):
        if word not in self.word2index:
            # First entry of word into vocabulary
            self.word2index[word] = self.num_words
            self.word2count[word] = 1
            self.index2word[self.num_words] = word
            self.num_words += 1
        else:
            # Word exists; increase word count
            self.word2count[word] += 1
            
    def add_sentence(self, sentence):
        sentence_len = 0
        for word in sentence.split(' '):
            sentence_len += 1
            self.add_word(word)
        if sentence_len > self.longest_sentence:
            # This is the longest sentence
            self.longest_sentence = sentence_len
        # Count the number of sentences
        self.num_sentences += 1

    def to_word(self, index):
        return self.index2word[index]

    def to_index(self, word):
        return self.word2index[word]

In [ ]:
voc = Vocabulary('test')
print(voc)

In [ ]:
corpus = ["I want to go out.",
             " I like to play.",
             " No eating - ",
             "No play!",
            ]


print(corpus)

['I want to go out.', ' I like to play.', ' No eating - ', 'No play!']


In [ ]:
for sent in corpus:
  voc.add_sentence(sent)
print(voc.word2index)

{'I': 3, 'want': 4, 'to': 5, 'go': 6, 'out.': 7, '': 8, 'like': 9, 'play.': 10, 'No': 11, 'eating': 12, '-': 13, 'play!': 14}
{0: 'PAD', 1: 'SOS', 2: 'EOS', 3: 'I', 4: 'want', 5: 'to', 6: 'go', 7: 'out.', 8: '', 9: 'like', 10: 'play.', 11: 'No', 12: 'eating', 13: '-', 14: 'play!'}


In [ ]:
print('Token 4 corresponds to token:', voc.to_word(4))
print('Token "this" corresponds to index:', voc.to_index('this'))

Token 4 corresponds to token: is
Token "this" corresponds to index: 22


In [ ]:
sen = ""
for word in range(voc.num_words):
    print(voc.to_word(word))

PAD
SOS
EOS
I
want
to
go
out.

like
play.
No
eating
-
play!


In [ ]:
sent_tkns = []
sent_idxs = []
for word in corpus[3].split(' '):
  sent_tkns.append(word)
  sent_idxs.append(voc.to_index(word))
print(sent_tkns)
print(sent_idxs)

['No', 'play!']
[30, 33]


In [ ]:
documents = ["I like this movie, it's funny.", 'I hate this movie.', 'This was awesome! I like it.', 'Nice one. I love it.']

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer
import pandas as pd

# Step 2. Design the Vocabulary
# The default token pattern removes tokens of a single character. That's why we don't have the "I" and "s" tokens in the output
count_vectorizer = CountVectorizer()

# Step 3. Create the Bag-of-Words Model
bag_of_words = count_vectorizer.fit_transform(documents)

# Show the Bag-of-Words Model as a pandas DataFrame
feature_names = count_vectorizer.get_feature_names()
pd.DataFrame(bag_of_words.toarray(), columns = feature_names)

/usr/local/lib/python3.7/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)


awesome  funny  hate  like  love  movie  nice
0        0      1     0     1     0      1     0
1        0      0     1     0     0      1     0
2        1      0     0     1     0      0     0
3        0      0     0     0     1      0     1

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer
import pandas as pd

tfidf_vectorizer = TfidfVectorizer()
values = tfidf_vectorizer.fit_transform(documents)

# Show the Model as a pandas DataFrame
feature_names = tfidf_vectorizer.get_feature_names()
pd.DataFrame(values.toarray(), columns = feature_names)

/usr/local/lib/python3.7/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)


awesome     funny      hate        it      like      love     movie  \
0  0.000000  0.571848  0.000000  0.365003  0.450852  0.000000  0.450852   
1  0.000000  0.000000  0.702035  0.000000  0.000000  0.000000  0.553492   
2  0.539445  0.000000  0.000000  0.344321  0.425305  0.000000  0.000000   
3  0.000000  0.000000  0.000000  0.345783  0.000000  0.541736  0.000000   

       nice       one      this       was  
0  0.000000  0.000000  0.365003  0.000000  
1  0.000000  0.000000  0.448100  0.000000  
2  0.000000  0.000000  0.344321  0.539445  
3  0.541736  0.541736  0.000000  0.000000

#SkipGram in Pytorch

In [ ]:
corpus = [
    'he is a king',
    'she is a queen',
    'he is a man',
    'she is a woman',
    'warsaw is poland capital',
    'berlin is germany capital',
    'paris is france capital',
]

In [ ]:
def tokenize_corpus(corpus):
    tokens = [x.split() for x in corpus]
    return tokens

tokenized_corpus = tokenize_corpus(corpus)
vocabulary = []
for sentence in tokenized_corpus:
    for token in sentence:
        if token not in vocabulary:
            vocabulary.append(token)

word2idx = {w: idx for (idx, w) in enumerate(vocabulary)}
idx2word = {idx: w for (idx, w) in enumerate(vocabulary)}

vocabulary_size = len(vocabulary)

print(word2idx)
print(idx2word)
print(vocabulary)

{'he': 0, 'is': 1, 'a': 2, 'king': 3, 'she': 4, 'queen': 5, 'man': 6, 'woman': 7, 'warsaw': 8, 'poland': 9, 'capital': 10, 'berlin': 11, 'germany': 12, 'paris': 13, 'france': 14}
{0: 'he', 1: 'is', 2: 'a', 3: 'king', 4: 'she', 5: 'queen', 6: 'man', 7: 'woman', 8: 'warsaw', 9: 'poland', 10: 'capital', 11: 'berlin', 12: 'germany', 13: 'paris', 14: 'france'}
['he', 'is', 'a', 'king', 'she', 'queen', 'man', 'woman', 'warsaw', 'poland', 'capital', 'berlin', 'germany', 'paris', 'france']


In [ ]:
import numpy as np

window_size = 2
idx_pairs = []
for sentence in tokenized_corpus:                                                         # for each sentence
    indices = [word2idx[word] for word in sentence]
    for center_word_pos in range(len(indices)):                                           # for each word, threated as center word
        for w in range(-window_size, window_size + 1):                                    # for each window position
            context_word_pos = center_word_pos + w                                        # make sure not jump out sentence
            if context_word_pos < 0 or context_word_pos >= len(indices) or center_word_pos == context_word_pos:
                continue
            context_word_idx = indices[context_word_pos]
            idx_pairs.append((indices[center_word_pos], context_word_idx))
    # print(indices)
    break

idx_pairs = np.array(idx_pairs)                                                           # it will be useful to have this as numpy array
print(tokenized_corpus[0])
for i in idx_pairs:
  print(idx2word[i[0]],idx2word[i[1]])

['he', 'is', 'a', 'king']
he is
he a
is he
is a
is king
a he
a is
a king
king is
king a


In [ ]:
import torch
from torch.autograd import Variable
import torch.nn.functional as F


In [ ]:
def get_input_layer(word_idx):
    x = torch.zeros(vocabulary_size).float()
    x[word_idx] = 1.0
    return x

In [ ]:
print(idx_pairs)

[[0 1]
 [0 2]
 [1 0]
 [1 2]
 [1 3]
 [2 0]
 [2 1]
 [2 3]
 [3 1]
 [3 2]]


In [ ]:
embedding_dims = 5
W1 = Variable(torch.randn(embedding_dims, vocabulary_size).float(), requires_grad=True)
W2 = Variable(torch.randn(vocabulary_size, embedding_dims).float(), requires_grad=True)
num_epochs = 101
learning_rate = 0.001


for epo in range(num_epochs):
    loss_val = 0
    for data, target in idx_pairs:
        x = Variable(get_input_layer(data)).float()
        # print(x)
        y_true = Variable(torch.from_numpy(np.array([target])).long())

        z1 = torch.matmul(W1, x)
        z2 = torch.matmul(W2, z1)
    
        log_softmax = F.log_softmax(z2, dim=0)

        loss = F.nll_loss(log_softmax.view(1,-1), y_true)
        loss_val += loss.item()
        loss.backward()
        
        W1.data -= learning_rate * W1.grad.data
        W2.data -= learning_rate * W2.grad.data

        W1.grad.data.zero_()
        W2.grad.data.zero_()
    
    if epo % 10 == 0:    
        print(f'Loss at epo {epo}: {loss_val/len(idx_pairs)}')


Loss at epo 0: 4.091924154758454
Loss at epo 10: 3.9284665405750276
Loss at epo 20: 3.7859984934329987
Loss at epo 30: 3.6624924719333647
Loss at epo 40: 3.555117219686508
Loss at epo 50: 3.460879999399185
Loss at epo 60: 3.37708575129509
Loss at epo 70: 3.301531380414963
Loss at epo 80: 3.232516181468964
Loss at epo 90: 3.1687616646289825
Loss at epo 100: 3.1093174695968626


In [46]:
import torch
import torch.nn as nn
import matplotlib.pyplot as plt


In [47]:
raw_text = """During my second month of nursing school, our professor gave us a pop quiz.  
I was a conscientious student and had breezed through the questions, until I read the last one: 
“What is the first name of the woman who cleans the school?”  Surely this was some kind of joke. 
I had seen the cleaning woman several times. She was tall, dark-haired and in her 50s, but how would I know her name?  
I handed in my paper, leaving the last question blank.  Before class ended, one student asked if the last question would count toward our quiz grade.  
“Absolutely,” said the professor.  “In your careers you will meet many people. All are significant. They deserve your attention and care, 
even if all you do is smile and say ‘hello’. I’ve never forgotten that lesson. I also learned her name was Dorothy.""".split()

In [49]:
CONTEXT_SIZE = 2  # 2 words to the left, 2 to the right
EMDEDDING_DIM = 100

# By deriving a set from `raw_text`, we deduplicate the array
vocab = set(raw_text)
vocab_size = len(vocab)

word_list = list(vocab)

word_to_ix = {word:ix for ix, word in enumerate(vocab)}
ix_to_word = {ix:word for ix, word in enumerate(vocab)}




In [52]:
print(vocab)
print(vocab_size)
print(word_to_ix)
print(ix_to_word)

{'significant.', '“Absolutely,”', 'read', 'that', 'a', 'lesson.', 'pop', 'name?', 'school?”', 'student', 'During', 'say', 'conscientious', '“In', 'breezed', 'asked', 'I', 'joke.', 'grade.', 'of', 'dark-haired', 'some', 'deserve', 'professor.', 'They', 'if', 'people.', 'one', 'her', 'count', 'professor', 'paper,', 'Before', 'how', 'seen', 'many', 'second', 'is', 'had', 'woman', 'meet', 'She', 'careers', 'in', 'toward', 'my', 'questions,', 'but', 'cleans', 'blank.', 'ended,', 'gave', 'and', 'several', 'school,', 'last', 'Dorothy.', 'also', 'kind', 'quiz', 'your', 'all', '‘hello’.', '50s,', 'Surely', 'us', 'through', 'even', 'learned', 'one:', 'know', 'care,', 'who', 'until', 'All', 'times.', 'quiz.', 'would', 'you', 'I’ve', 'smile', 'our', 'never', 'month', 'do', 'said', 'tall,', 'class', 'cleaning', 'are', 'forgotten', 'leaving', 'the', 'question', 'this', 'attention', 'handed', 'will', 'nursing', 'first', 'was', 'name', '“What'}
103
{'significant.': 0, '“Absolutely,”': 1, 'read': 2, 't

In [61]:
"""During my second month of nursing school"""
def CBOW(raw_text, window_size=2):
    data = []
    for i in range(window_size, len(raw_text) - window_size):
        context = [raw_text[i - window_size], raw_text[i - (window_size - 1)], raw_text[i + (window_size - 1)], raw_text[i + window_size]]
        
        # context = raw_text[i - window_size:i + window_size+1]
        # context.remove(raw_text[i])                                        //Alternate Way of finding Context Words
        
        target = raw_text[i]
        data.append((context, target))

    return data


data = CBOW(raw_text)
data[:10]

[(['During', 'my', 'month', 'of'], 'second'),
 (['my', 'second', 'of', 'nursing'], 'month'),
 (['second', 'month', 'nursing', 'school,'], 'of'),
 (['month', 'of', 'school,', 'our'], 'nursing'),
 (['of', 'nursing', 'our', 'professor'], 'school,'),
 (['nursing', 'school,', 'professor', 'gave'], 'our'),
 (['school,', 'our', 'gave', 'us'], 'professor'),
 (['our', 'professor', 'us', 'a'], 'gave'),
 (['professor', 'gave', 'a', 'pop'], 'us'),
 (['gave', 'us', 'pop', 'quiz.'], 'a')]

In [116]:
class CBOW_Model(torch.nn.Module):
    def __init__(self, vocab_size, embedding_dim):
        super(CBOW_Model, self).__init__()

        #out: 1 x emdedding_dim
        self.embeddings = nn.Embedding(vocab_size, embedding_dim)
        self.linear1 = nn.Linear(embedding_dim, 128)
        self.activation_function1 = nn.ReLU()
        
        #out: 1 x vocab_size
        self.linear2 = nn.Linear(128, vocab_size)
        

    def forward(self, inputs):
        # print(sum(self.embeddings(inputs)).view(1,-1))
        embeds = sum(self.embeddings(inputs)).view(1,-1)
        out = self.linear1(embeds)
        out = self.activation_function1(out)
        out = self.linear2(out)
        # print("Output:",out)
        return out

    def get_word_emdedding(self, word):
        word = torch.tensor([word_to_ix[word]])
        return self.embeddings(word).view(1,-1)

In [117]:
model = CBOW_Model(vocab_size, EMDEDDING_DIM)

loss_function = nn.CrossEntropyLoss()
optimizer = torch.optim.SGD(model.parameters(), lr=0.01)

In [118]:
data[0]

(['During', 'my', 'month', 'of'], 'second')

In [119]:
def make_context_vector(context, word_to_ix):
    idxs = [word_to_ix[w] for w in context]
    return torch.tensor(idxs, dtype=torch.long)

In [ ]:
torch.tensor([word_to_ix[target]])
target,log_probs

In [120]:
#TRAINING
for epoch in range(1):
    total_loss = 0

    for context, target in data:
        context_vector = make_context_vector(context, word_to_ix)  

        log_probs = model(context_vector)

        total_loss += loss_function(log_probs, torch.tensor([word_to_ix[target]]))

        break

        
    # if epoch%10==0:
    #       print("Epoch {}: {}".format(epoch,total_loss.data))
        
    optimizer.zero_grad()
    total_loss.backward()
    optimizer.step()

Output: tensor([[-7.8853e-02, -1.4675e-01,  4.6027e-01,  1.3036e+00, -1.7556e-01,
         -1.4308e-01, -2.7179e-01, -1.1886e-02,  2.9907e-01, -4.1299e-01,
          6.7182e-02,  9.4632e-01, -5.4379e-01, -9.7060e-01, -2.2507e-01,
          4.7415e-01,  2.8251e-01, -9.9908e-01, -5.3166e-02,  5.5032e-01,
         -2.1709e-01, -5.6844e-01,  7.4841e-01,  7.8129e-01, -2.0405e-01,
         -4.7772e-02,  1.6196e-01, -4.3125e-01,  1.0856e-01, -3.3955e-02,
          6.5667e-01,  1.3472e+00,  1.1816e+00,  1.3983e-01, -7.6802e-01,
          1.4598e-01, -4.9751e-01, -7.4870e-01, -7.0096e-01, -1.2812e+00,
          5.2469e-01,  2.6806e-02,  3.2783e-01, -5.2668e-01, -9.4038e-01,
         -4.1887e-01,  6.6365e-01,  5.9331e-01,  8.7224e-01, -2.3898e-01,
         -1.3840e-01,  1.6173e-01, -8.8392e-01,  9.0439e-01, -8.3500e-02,
         -1.3209e-02, -2.5065e-02, -8.0487e-01,  1.4557e-02, -9.1774e-01,
          5.0811e-01,  1.0900e-01,  3.3819e-01, -3.8244e-02, -5.4471e-01,
         -2.4600e-01, -9.2689e